import type { HealthMetric } from './types';

export const HEALTH_METRICS: HealthMetric[] = [
  { id: 'heart_pulse', name: 'Heart rate & blood pressure', category: 'cardiovascular', weight: 0.12,
    description: 'Your heart rate and blood pressure begin to drop within minutes.',
    disclaimer: 'Estimated recovery indicator based on WHO cessation guidance.',
    milestones: [
      { hours_after_quitting: 0.33, progress: 40, description: 'Heart rate begins to return toward baseline.', source: 'WHO', confidence: 'high' },
      { hours_after_quitting: 24, progress: 75, description: 'Blood pressure typically stabilises.', source: 'WHO / NHS', confidence: 'high' },
      { hours_after_quitting: 336, progress: 90, description: 'Cardiovascular strain noticeably reduced.', source: 'NHS', confidence: 'moderate' },
      { hours_after_quitting: 8760, progress: 100, description: 'Coronary heart disease risk ~half of a smoker.', source: 'WHO', confidence: 'high' },
    ]},
  { id: 'carbon_monoxide', name: 'Carbon monoxide', category: 'systemic', weight: 0.10,
    description: 'Carbon monoxide in your blood is being cleared.',
    disclaimer: 'Blood CO levels return to non-smoker range in 12–48 hours for most people.',
    milestones: [
      { hours_after_quitting: 8, progress: 50, description: 'CO levels dropping; oxygen rising.', source: 'HSE Ireland', confidence: 'high' },
      { hours_after_quitting: 12, progress: 85, description: 'Blood CO near normal.', source: 'WHO', confidence: 'high' },
      { hours_after_quitting: 48, progress: 100, description: 'CO effectively eliminated.', source: 'NHS', confidence: 'high' },
    ]},
  { id: 'nicotine', name: 'Nicotine clearance', category: 'systemic', weight: 0.08,
    description: 'Nicotine is being eliminated from your body.',
    disclaimer: 'Nicotine elimination half-life is roughly 2 hours.',
    milestones: [
      { hours_after_quitting: 2, progress: 40, description: 'Nicotine half-life reached.', source: 'FDA', confidence: 'high' },
      { hours_after_quitting: 12, progress: 80, description: 'Most nicotine cleared.', source: 'NHS', confidence: 'high' },
      { hours_after_quitting: 72, progress: 98, description: 'Cotinine levels effectively cleared.', source: 'Peer-reviewed', confidence: 'moderate' },
      { hours_after_quitting: 96, progress: 100, description: 'Nicotine fully metabolised.', source: 'FDA', confidence: 'moderate' },
    ]},
  { id: 'oxygen_circulation', name: 'Oxygen & circulation', category: 'cardiovascular', weight: 0.10,
    description: 'Oxygen levels are recovering; blood is less thick and sticky.',
    disclaimer: 'Circulation improvements continue gradually over 2–12 weeks.',
    milestones: [
      { hours_after_quitting: 8, progress: 30, description: 'Oxygen levels rising.', source: 'HSE Ireland', confidence: 'high' },
      { hours_after_quitting: 336, progress: 70, description: 'Circulation improving throughout body.', source: 'WHO', confidence: 'high' },
      { hours_after_quitting: 2016, progress: 90, description: 'Blood is less thick and sticky.', source: 'Health.gov.au', confidence: 'moderate' },
      { hours_after_quitting: 4320, progress: 100, description: 'Blood flow to hands and feet improved.', source: 'Health.gov.au', confidence: 'moderate' },
    ]},
  { id: 'breathing', name: 'Breathing & lung function', category: 'respiratory', weight: 0.14,
    description: 'Your respiratory system is beginning its recovery.',
    disclaimer: 'Lung function improvements are gradual and continue for months.',
    milestones: [
      { hours_after_quitting: 24, progress: 10, description: 'Lungs begin clearing mucus.', source: 'MedlinePlus', confidence: 'high' },
      { hours_after_quitting: 72, progress: 25, description: 'Breathing becomes noticeably easier.', source: 'PMC', confidence: 'high' },
      { hours_after_quitting: 336, progress: 55, description: 'Lung function starts increasing.', source: 'WHO', confidence: 'high' },
      { hours_after_quitting: 2160, progress: 80, description: 'Coughing and shortness of breath decrease.', source: 'WHO', confidence: 'high' },
      { hours_after_quitting: 8760, progress: 95, description: 'Significant lung function recovery.', source: 'WHO', confidence: 'moderate' },
    ]},
  { id: 'energy', name: 'Energy levels', category: 'systemic', weight: 0.06,
    description: 'Energy levels can improve as your body adjusts to being smoke-free.',
    disclaimer: 'Subjective; varies greatly between individuals.',
    milestones: [
      { hours_after_quitting: 8, progress: 25, description: 'Early energy lift as CO clears.', source: 'NHS', confidence: 'moderate' },
      { hours_after_quitting: 72, progress: 50, description: 'Energy levels increasing.', source: 'BHF', confidence: 'moderate' },
      { hours_after_quitting: 672, progress: 80, description: 'Sustained energy improvements.', source: 'NHS', confidence: 'estimated' },
      { hours_after_quitting: 2160, progress: 100, description: 'Exercise feels easier.', source: 'NHS', confidence: 'moderate' },
    ]},
  { id: 'taste_smell', name: 'Taste & smell', category: 'sensory', weight: 0.06,
    description: 'Your senses of taste and smell are recovering.',
    disclaimer: 'Most people notice improvement within 48 hours to a week.',
    milestones: [
      { hours_after_quitting: 48, progress: 60, description: 'Taste and smell beginning to improve.', source: 'PMC', confidence: 'high' },
      { hours_after_quitting: 168, progress: 85, description: 'Large part of lost senses recovered.', source: 'Jules Bordet', confidence: 'moderate' },
      { hours_after_quitting: 336, progress: 100, description: 'Taste and smell typically restored.', source: 'PMC', confidence: 'moderate' },
    ]},
  { id: 'bad_breath', name: 'Bad breath', category: 'oral', weight: 0.04,
    description: 'Smoke-related bad breath is improving.',
    disclaimer: 'Depends on oral hygiene; smoking-related halitosis improves within days.',
    milestones: [
      { hours_after_quitting: 48, progress: 60, description: 'Breath noticeably fresher.', source: 'HK Gov Health', confidence: 'moderate' },
      { hours_after_quitting: 168, progress: 100, description: 'Smoke-related odour cleared.', source: 'HK Gov Health', confidence: 'moderate' },
    ]},
  { id: 'gums_teeth', name: 'Gums & teeth', category: 'oral', weight: 0.06,
    description: 'Gum circulation is returning and inflammation is reducing.',
    disclaimer: 'Gum health returns to normal in about 12 months.',
    milestones: [
      { hours_after_quitting: 72, progress: 15, description: 'Gingival oxygen saturation improving.', source: 'Dentalpedia', confidence: 'moderate' },
      { hours_after_quitting: 2160, progress: 45, description: 'Oral mucosa in better condition.', source: 'Peer-reviewed', confidence: 'moderate' },
      { hours_after_quitting: 8760, progress: 100, description: 'Gums typically back to health.', source: 'Peer-reviewed', confidence: 'moderate' },
    ]},
  { id: 'sexual_health', name: 'Sexual health', category: 'sexual', weight: 0.10,
    description: 'Smoking can affect blood vessels and circulation, which can contribute to erectile difficulties. Quitting smoking may support vascular and sexual health over time.',
    disclaimer: 'Estimated recovery indicator, not a diagnosis. Talk to a healthcare professional if you have persistent erectile difficulties.',
    milestones: [
      { hours_after_quitting: 36, progress: 15, description: 'Measurable penile blood-flow improvement observed in studies.', source: 'ScienceDirect 2007', confidence: 'moderate' },
      { hours_after_quitting: 336, progress: 40, description: 'Circulation improvements support vascular health.', source: 'WHO', confidence: 'moderate' },
      { hours_after_quitting: 4320, progress: 70, description: 'Studies show improvement in ED grade in ~25% of ex-smokers.', source: 'Eur Urol', confidence: 'moderate' },
      { hours_after_quitting: 8760, progress: 90, description: 'Long-term vascular recovery continues.', source: 'Eur Urol', confidence: 'moderate' },
    ]},
];
